import type { Pilot, ShowcaseItem } from "./types";

// Demo-data voor de publieke site. In productie komt dit uit Supabase.
// Realistisch genoeg om de matching, gids en showcase te tonen.

export const PILOTS: Pilot[] = [
  {
    slug: "lars-de-vries",
    name: "Lars de Vries",
    company: "Skyframe Media",
    citySlug: "amsterdam",
    region: "Randstad",
    country: "NL",
    tier: "silver",
    membership: "pro",
    verified: true,
    certs: ["advanced"],
    insured: true,
    operatorId: "NLD••••4821",
    segments: ["vastgoed", "marketing", "evenementen"],
    serviceRadiusKm: 45,
    rating: 4.9,
    reviewCount: 38,
    jobsDone: 142,
    responseTime: "< 1 uur",
    gear: ["DJI Mavic 4 Pro", "DJI Air 3S"],
    bio: "Cinematograaf met 6 jaar drone-ervaring. Gespecialiseerd in vastgoed- en merkvideo voor makelaars en hotels in de Randstad. Snel, betrouwbaar, Funda-klaar.",
    reviews: [
      { author: "Marit K.", role: "Makelaar", city: "Amsterdam", rating: 5, text: "Binnen 48 uur prachtige beelden van een grachtenpand. Verkocht in een week." },
      { author: "Boutique Hotel Prinsen", role: "Marketing", city: "Amsterdam", rating: 5, text: "Onze Reels gingen door het dak. Top samenwerking." },
    ],
  },
  {
    slug: "sanne-bakker",
    name: "Sanne Bakker",
    company: "Hoogzicht Inspecties",
    citySlug: "rotterdam",
    region: "Randstad",
    country: "NL",
    tier: "gold",
    membership: "elite",
    verified: true,
    certs: ["advanced", "specific"],
    insured: true,
    operatorId: "NLD••••9173",
    segments: ["inspectie", "zonnepanelen", "bouw"],
    serviceRadiusKm: 60,
    rating: 4.8,
    reviewCount: 51,
    jobsDone: 210,
    responseTime: "< 2 uur",
    gear: ["DJI Matrice 4T", "Zenmuse H30T"],
    bio: "Specialist in technische inspectie en thermografie. STS-01 gecertificeerd, €2M verzekerd. Levert heldere rapporten voor VvE's, installateurs en bouwbedrijven.",
    reviews: [
      { author: "VvE Maasoever", role: "Beheerder", city: "Rotterdam", rating: 5, text: "Daklekkage exact gelokaliseerd zonder steiger. Scheelde duizenden euro's." },
      { author: "Zon&Co", role: "Installateur", city: "Rotterdam", rating: 4, text: "Thermografie van ons zonnepark was vlekkeloos." },
    ],
  },
  {
    slug: "youssef-amrani",
    name: "Youssef Amrani",
    company: "Vlucht3D",
    citySlug: "utrecht",
    region: "Randstad",
    country: "NL",
    tier: "platinum",
    membership: "elite",
    verified: true,
    certs: ["advanced", "specific", "org"],
    insured: true,
    operatorId: "NLD••••2056",
    segments: ["landmeten", "bouw", "inspectie"],
    serviceRadiusKm: 80,
    rating: 5.0,
    reviewCount: 27,
    jobsDone: 96,
    responseTime: "< 3 uur",
    gear: ["DJI Matrice 400", "Zenmuse L2 LiDAR"],
    bio: "Landmeetkundige met operationele autorisatie voor complexe projecten. LiDAR-puntwolken en orthomosaïeken met RTK-nauwkeurigheid voor ingenieurs en gemeenten.",
    reviews: [
      { author: "Ingenieursbureau Tauw", role: "Projectleider", city: "Utrecht", rating: 5, text: "Centimeter-nauwkeurige data, perfect aangeleverd in ons GIS." },
    ],
  },
  {
    slug: "emma-visser",
    name: "Emma Visser",
    company: "Emma Visser Films",
    citySlug: "den-haag",
    region: "Randstad",
    country: "NL",
    tier: "platinum",
    membership: "pro",
    verified: true,
    certs: ["advanced"],
    insured: true,
    operatorId: "NLD••••6634",
    segments: ["marketing", "evenementen", "vastgoed"],
    serviceRadiusKm: 50,
    rating: 4.9,
    reviewCount: 44,
    jobsDone: 168,
    responseTime: "< 1 uur",
    gear: ["DJI Inspire 3", "DJI Mavic 4 Pro"],
    bio: "Cinematische merkfilms met de Inspire 3 (8K). Werkt voor reclamebureaus en toerisme. Volledige crew mogelijk voor commercials.",
    reviews: [
      { author: "Bureau Noord", role: "Creative Director", city: "Den Haag", rating: 5, text: "Bioscoopkwaliteit. Onze klant was sprakeloos." },
    ],
  },
  {
    slug: "tom-jansen",
    name: "Tom Jansen",
    company: "Jansen Luchtfoto",
    citySlug: "eindhoven",
    region: "Brabant",
    country: "NL",
    tier: "bronze",
    membership: "free",
    verified: true,
    certs: ["basic"],
    insured: true,
    operatorId: "NLD••••3390",
    segments: ["vastgoed", "evenementen"],
    serviceRadiusKm: 40,
    rating: 4.7,
    reviewCount: 19,
    jobsDone: 64,
    responseTime: "< 4 uur",
    gear: ["DJI Mini 5 Pro"],
    bio: "Betaalbare luchtfoto's voor woningen en kleine evenementen in Brabant. Snelle levering, scherpe prijs.",
    reviews: [
      { author: "Huis & Co Makelaars", role: "Makelaar", city: "Eindhoven", rating: 5, text: "Prima foto's, nette prijs, snel geleverd." },
    ],
  },
  {
    slug: "lotte-meijer",
    name: "Lotte Meijer",
    company: "GroenZicht Agro",
    citySlug: "zwolle",
    region: "Oost",
    country: "NL",
    tier: "gold",
    membership: "pro",
    verified: true,
    certs: ["advanced", "specific"],
    insured: true,
    operatorId: "NLD••••7745",
    segments: ["agrarisch", "landmeten", "inspectie"],
    serviceRadiusKm: 70,
    rating: 4.8,
    reviewCount: 22,
    jobsDone: 88,
    responseTime: "< 3 uur",
    gear: ["DJI Mavic 3 Multispectral", "Matrice 4E"],
    bio: "Precisielandbouw vanuit de lucht. NDVI-kaarten en gewasmonitoring voor telers en loonwerkers in Oost-Nederland.",
    reviews: [
      { author: "Akkerbouw Veldhof", role: "Teler", city: "Zwolle", rating: 5, text: "Droogtestress vroeg gespot, scheelde een deel van de oogst." },
    ],
  },
  {
    slug: "david-koster",
    name: "David Koster",
    company: "Koster Aerial",
    citySlug: "groningen",
    region: "Noord",
    country: "NL",
    tier: "gold",
    membership: "pro",
    verified: true,
    certs: ["advanced", "specific"],
    insured: true,
    operatorId: "NLD••••1208",
    segments: ["zonnepanelen", "bouw", "inspectie"],
    serviceRadiusKm: 75,
    rating: 4.6,
    reviewCount: 17,
    jobsDone: 73,
    responseTime: "< 4 uur",
    gear: ["DJI Matrice 4T", "Zenmuse H30T"],
    bio: "Thermografie en inspectie in Noord-Nederland. Veel ervaring met zonneparken en windenergie-gerelateerde inspecties.",
    reviews: [
      { author: "SolarNoord", role: "Asset manager", city: "Groningen", rating: 5, text: "Heldere rapportage van 12.000 panelen. Aanrader." },
    ],
  },
  {
    slug: "nina-smit",
    name: "Nina Smit",
    company: "Smit Visuals",
    citySlug: "haarlem",
    region: "Randstad",
    country: "NL",
    tier: "silver",
    membership: "pro",
    verified: true,
    certs: ["advanced"],
    insured: true,
    operatorId: "NLD••••5519",
    segments: ["marketing", "vastgoed", "evenementen"],
    serviceRadiusKm: 40,
    rating: 4.9,
    reviewCount: 31,
    jobsDone: 119,
    responseTime: "< 1 uur",
    gear: ["DJI Mavic 4 Pro"],
    bio: "Social-first dronecontent voor merken en makelaars in en rond Amsterdam. Sterk in verticale video voor Reels en TikTok.",
    reviews: [
      { author: "Studio Bloei", role: "Content lead", city: "Haarlem", rating: 5, text: "Begrijpt social als geen ander. Snel schakelen." },
    ],
  },
  {
    slug: "ruben-postma",
    name: "Ruben Postma",
    company: "Postma Survey",
    citySlug: "breda",
    region: "Brabant",
    country: "NL",
    tier: "gold",
    membership: "elite",
    verified: false,
    certs: ["advanced", "specific"],
    insured: true,
    operatorId: "NLD••••8842",
    segments: ["landmeten", "bouw"],
    serviceRadiusKm: 65,
    rating: 4.7,
    reviewCount: 14,
    jobsDone: 52,
    responseTime: "< 5 uur",
    gear: ["Matrice 4E", "RTK-module"],
    bio: "Bouw- en infraprojecten in Brabant. Voortgangsmonitoring en orthomosaïeken voor aannemers. Verificatie in behandeling.",
    reviews: [
      { author: "Bouwgroep Zuid", role: "Uitvoerder", city: "Breda", rating: 5, text: "Maandelijkse voortgangsbeelden, altijd op tijd." },
    ],
  },
  {
    slug: "james-whitfield",
    name: "James Whitfield",
    company: "Whitfield Aerials",
    citySlug: "london",
    region: "England",
    country: "GB",
    tier: "silver",
    membership: "pro",
    verified: true,
    certs: ["advanced"],
    insured: true,
    operatorId: "GBR-OP-••8841",
    segments: ["vastgoed", "marketing", "evenementen"],
    serviceRadiusKm: 50,
    rating: 4.9,
    reviewCount: 41,
    jobsDone: 158,
    responseTime: "< 1 hour",
    gear: ["DJI Mavic 4 Pro", "DJI Air 3S"],
    bio: "London-based aerial cinematographer for estate agents, hotels and brands. CAA A2 CofC, £5M insured. Fast, Rightmove-ready delivery across Greater London.",
    reviews: [
      { author: "Harcourt Estates", role: "Estate agent", city: "London", rating: 5, text: "Stunning aerials of a riverside listing, delivered in 48 hours. Sold within the week." },
    ],
  },
  {
    slug: "priya-sharma",
    name: "Priya Sharma",
    company: "Skyhigh Surveys",
    citySlug: "manchester",
    region: "England",
    country: "GB",
    tier: "gold",
    membership: "elite",
    verified: true,
    certs: ["advanced", "specific"],
    insured: true,
    operatorId: "GBR-OP-••2207",
    segments: ["inspectie", "zonnepanelen", "bouw"],
    serviceRadiusKm: 65,
    rating: 4.8,
    reviewCount: 47,
    jobsDone: 196,
    responseTime: "< 2 hours",
    gear: ["DJI Matrice 4T", "Zenmuse H30T"],
    bio: "Thermal and structural inspection specialist. CAA GVC + PDRA01, £5M public liability. Clear reports for facilities managers, solar operators and contractors.",
    reviews: [
      { author: "Pennine FM", role: "Facilities manager", city: "Manchester", rating: 5, text: "Pinpointed roof damage without scaffolding. Saved us thousands." },
    ],
  },
  {
    slug: "callum-brown",
    name: "Callum Brown",
    company: "Highland Drone",
    citySlug: "glasgow",
    region: "Scotland",
    country: "GB",
    tier: "gold",
    membership: "pro",
    verified: true,
    certs: ["advanced", "specific"],
    insured: true,
    operatorId: "GBR-OP-••5562",
    segments: ["landmeten", "bouw", "agrarisch"],
    serviceRadiusKm: 90,
    rating: 4.7,
    reviewCount: 19,
    jobsDone: 71,
    responseTime: "< 4 hours",
    gear: ["DJI Matrice 400", "Zenmuse L2 LiDAR"],
    bio: "Surveying and mapping across central Scotland. CAA Operational Authorisation, RTK-accurate orthomosaics and LiDAR for engineers and councils.",
    reviews: [
      { author: "Clyde Civil", role: "Project lead", city: "Glasgow", rating: 5, text: "Centimetre-accurate site data, delivered straight into our GIS." },
    ],
  },
  {
    slug: "lukas-mueller",
    name: "Lukas Müller",
    company: "Rheinblick Luftbild",
    citySlug: "koeln",
    region: "NRW",
    country: "DE",
    tier: "silver",
    membership: "pro",
    verified: true,
    certs: ["advanced"],
    insured: true,
    operatorId: "DEU-••3390",
    segments: ["vastgoed", "marketing", "evenementen"],
    serviceRadiusKm: 55,
    rating: 4.9,
    reviewCount: 33,
    jobsDone: 124,
    responseTime: "< 1 Stunde",
    gear: ["DJI Mavic 4 Pro"],
    bio: "Luftbild- und Markenvideo für Makler, Hotels und Agenturen im Rheinland. EU-Kompetenznachweis A2, 1 Mio. € versichert. Schnelle, hochwertige Lieferung.",
    reviews: [
      { author: "Immobilien Rhein", role: "Makler", city: "Köln", rating: 5, text: "Beeindruckende Aufnahmen, innerhalb von 48 Stunden geliefert. Sehr zu empfehlen." },
    ],
  },
  {
    slug: "anna-schmidt",
    name: "Anna Schmidt",
    company: "Ruhr Drohnen Service",
    citySlug: "dortmund",
    region: "Ruhrgebiet",
    country: "DE",
    tier: "gold",
    membership: "elite",
    verified: true,
    certs: ["advanced", "specific"],
    insured: true,
    operatorId: "DEU-••7745",
    segments: ["inspectie", "zonnepanelen", "bouw"],
    serviceRadiusKm: 70,
    rating: 4.8,
    reviewCount: 28,
    jobsDone: 102,
    responseTime: "< 3 Stunden",
    gear: ["DJI Matrice 4T", "Zenmuse H30T"],
    bio: "Thermografie und Inspektion im Ruhrgebiet. Betriebsgenehmigung (Specific), klare Berichte für Hausverwaltungen, Solarbetreiber und Bauunternehmen.",
    reviews: [
      { author: "SolarWest", role: "Asset Manager", city: "Dortmund", rating: 5, text: "Klare Auswertung von 9.000 Modulen. Absolute Empfehlung." },
    ],
  },
];

export function getPilot(slug: string): Pilot | undefined {
  return PILOTS.find((p) => p.slug === slug);
}

export const SHOWCASE: ShowcaseItem[] = [
  { id: "sc-1", title: "Grachtenpand bij avond", segment: "vastgoed", citySlug: "amsterdam", tier: "silver", pilotSlug: "lars-de-vries", isVideo: true },
  { id: "sc-2", title: "Daklekkage-inspectie", segment: "inspectie", citySlug: "rotterdam", tier: "gold", pilotSlug: "sanne-bakker", isVideo: false },
  { id: "sc-3", title: "Zonnepark thermografie", segment: "zonnepanelen", citySlug: "groningen", tier: "gold", pilotSlug: "david-koster", isVideo: false },
  { id: "sc-4", title: "Merkfilm kustlijn", segment: "marketing", citySlug: "den-haag", tier: "platinum", pilotSlug: "emma-visser", isVideo: true },
  { id: "sc-5", title: "LiDAR terreinscan", segment: "landmeten", citySlug: "utrecht", tier: "platinum", pilotSlug: "youssef-amrani", isVideo: false },
  { id: "sc-6", title: "Festival aftermovie", segment: "evenementen", citySlug: "eindhoven", tier: "silver", pilotSlug: "tom-jansen", isVideo: true },
  { id: "sc-7", title: "Nieuwbouw voortgang", segment: "bouw", citySlug: "breda", tier: "gold", pilotSlug: "ruben-postma", isVideo: false },
  { id: "sc-8", title: "NDVI gewaskaart", segment: "agrarisch", citySlug: "zwolle", tier: "gold", pilotSlug: "lotte-meijer", isVideo: false },
  { id: "sc-9", title: "Villa met tuin", segment: "vastgoed", citySlug: "haarlem", tier: "bronze", pilotSlug: "nina-smit", isVideo: false },
  { id: "sc-10", title: "Hotel rooftop Reel", segment: "marketing", citySlug: "amsterdam", tier: "silver", pilotSlug: "lars-de-vries", isVideo: true },
  { id: "sc-11", title: "Bedrijfspand 360°", segment: "vastgoed", citySlug: "utrecht", tier: "silver", pilotSlug: "nina-smit", isVideo: false },
  { id: "sc-12", title: "Gevelinspectie hoogbouw", segment: "inspectie", citySlug: "rotterdam", tier: "gold", pilotSlug: "sanne-bakker", isVideo: false },
];

// Trust/credibility cijfers (afgeleid van het marktonderzoek).
export const STATS = {
  activePilots: 50566,
  citiesCovered: CITIES_COUNT(),
  avgDelivery: "48–72u",
  avgRating: 4.8,
};

function CITIES_COUNT() {
  return 22;
}
